### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern-postman#35]
The Postman Generator has the following config:

```
  - name: fernapi/fern-postman
    version: 0.0.23
    mode: download-files
    output-path: ./generated-postman
    config:
      publishing:
        apiKey: ${POSTMAN_API_TOKEN}
        workspaceId: 7e790b68-d56f-4984-82c1-1beb234ae59d
```

It fails with: "Maximum call stack size exceeded"

Commit with bug: https://tinyurl.com/584848xy
