### ISSUE TITLE
Extends is not bringing in the properties to responses

### ISSUE THREAD

**Issue by dannysheridan** [fern-api/fern-postman#36]
```
  PaymentCardSchema:
    extends: PaymentMethodBase
    properties:
      paymentMethodData: PaymentCardTokenAPISchema
```

Properties that are missing in `PaymentCardSchema` for the Postman collection example of the wire format
```
  PaymentMethodBase:
    properties:
      descriptor: optional<string>
      paymentMethodToken: optional<string>
      isVaulted: optional<boolean>
      analyticsId: optional<string>
      threeDSecureAuthentication: optional<ThreeDSecureAuthentication>
```

<img width="1437" alt="Screen Shot 2022-10-11 at 1 02 45 PM" src="https://user-images.githubusercontent.com/83524670/195188065-6a85e953-c870-4f8a-9dce-e4ca3537c717.png">
